name: "CIM-Core Analysis"
description: "Run CIM-Core adaptive analysis directly inside GitHub workflows."
author: "ErvraTech"

branding:
  icon: "cpu"
  color: "blue"

inputs:
  api_key:
    description: "Your CIM-Core API key (store in GitHub Secrets)."
    required: true
  data_path:
    description: "Path to the input dataset (.csv / .json)."
    required: true
  config_file:
    description: "Optional path to a CIM-Core configuration file."
    required: false
  endpoint:
    description: "CIM-Core API endpoint URL."
    required: false
    default: "https://api.cim-core.com/analyze"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.api_key }}
    - ${{ inputs.data_path }}
    - ${{ inputs.config_file }}
    - ${{ inputs.endpoint }}
